/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ExpenseRequestsObjectPageObjectPage journey");

        opaTest("Navigate to ExpenseRequestsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheExpenseRequestsList.onFilterBar().iExecuteSearch();

            Then.onTheExpenseRequestsList.onTable().iCheckRows();
            When.onTheExpenseRequestsList.onTable().iPressRow(0);

            Then.onTheExpenseRequestsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheExpenseRequestsObjectPage.iCheckNumberOfSections(2);
            When.onTheExpenseRequestsObjectPage.iPressSectionIconTabFilterButton("GeneralInformation");
            Then.onTheExpenseRequestsObjectPage.iCheckSection({ section: "GeneralInformation" });
            Then.onTheExpenseRequestsObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "employeeID_BusinessPartner" });
            Then.onTheExpenseRequestsObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "companyCode_CompanyCode" });
            Then.onTheExpenseRequestsObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "currency_Currency" });
            Then.onTheExpenseRequestsObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "requestType_code" });
            Then.onTheExpenseRequestsObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "subRequestType_code" });
            Then.onTheExpenseRequestsObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "dateFiled" });
            Then.onTheExpenseRequestsObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "period" });
            Then.onTheExpenseRequestsObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "year" });
            Then.onTheExpenseRequestsObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "remarks" });
            Then.onTheExpenseRequestsObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "reference" });
            Then.onTheExpenseRequestsObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "department" });
            Then.onTheExpenseRequestsObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "costCenter_CostCenter" });
            Then.onTheExpenseRequestsObjectPage.onForm({ section: "GeneralInformation" }).iCheckField({ property: "area" });
            When.onTheExpenseRequestsObjectPage.iPressSectionIconTabFilterButton("Items");
            Then.onTheExpenseRequestsObjectPage.iCheckSection({ section: "Items" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});