/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ExpenseRequestsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheExpenseRequestsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheExpenseRequestsList.onFilterBar().iCheckFilterField("companyCode_CompanyCode");
            Then.onTheExpenseRequestsList.onFilterBar().iCheckFilterField("requestType_code");
            Then.onTheExpenseRequestsList.onFilterBar().iCheckFilterField("subRequestType_code");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheExpenseRequestsList.onTable().iCheckColumns(undefined, {"companyCode_CompanyCode":{"header":"companyCode_CompanyCode"},"employeeID_BusinessPartner":{"header":"employeeID_BusinessPartner"},"requestType_code":{"header":"requestType_code"},"subRequestType_code":{"header":"subRequestType_code"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheExpenseRequestsList.onFilterBar().iExecuteSearch();
            
            Then.onTheExpenseRequestsList.onTable().iCheckRows();

            When.onTheExpenseRequestsList.onTable().iPressRow(0);
            Then.onTheExpenseRequestsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});